# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.24.0' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.(([jt]sx?)|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@5.39.0'
          - '@vue/eslint-config-typescript@11.0.2'
          - eslint@8.24.0
          - eslint-config-prettier@8.5.0
          - eslint-plugin-prettier@4.2.1
          - eslint-plugin-vue@9.6.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.0' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types_or: [scss, css, javascript, vue, html, json, yaml]
