name: Node.js CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '>=17'
          cache: 'pnpm'

      - name: setup python
        uses: actions/setup-python@v2

      - name: build docs
        run: |
          pnpm install
          pnpm docs:build

      - name: Upload dist
        run: |
          python3 -m pip install coscmd
          coscmd config -a ${{ secrets.SecretId }} -s ${{ secrets.SecretKey }} -b graiax-1302360504 -r ap-hongkong
          coscmd delete -r -f /
          coscmd upload -r docs/.vuepress/dist/ /
